# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RegionInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10RegionInfo.proto\"\x85\x03\n\nRegionInfo\x12\x15\n\rgateserver_ip\x18\x01 \x01(\t\x12\x17\n\x0fgateserver_port\x18\x02 \x01(\r\x12\x1c\n\x14\x63lient_custom_config\x18\x03 \x01(\t\x12\x1c\n\x14region_custom_config\x18\x04 \x01(\t\x12\x13\n\x0b\x61\x63\x63ount_url\x18\x05 \x01(\t\x12\x17\n\x0f\x61\x63\x63ount_url_bak\x18\x06 \x01(\t\x12\x18\n\x10pay_callback_url\x18\x07 \x01(\t\x12\x14\n\x0cresource_url\x18\x08 \x01(\t\x12\x10\n\x08\x64\x61ta_url\x18\t \x01(\t\x12\x14\n\x0c\x66\x65\x65\x64\x62\x61\x63k_url\x18\n \x01(\t\x12\x14\n\x0c\x62ulletin_url\x18\x0b \x01(\t\x12\x18\n\x10resource_url_bak\x18\x0c \x01(\t\x12\x14\n\x0c\x64\x61ta_url_bak\x18\r \x01(\t\x12\x14\n\x0c\x64\x61ta_version\x18\x0e \x01(\r\x12\x13\n\x0bres_version\x18\x0f \x01(\r\x12\x14\n\x0chandbook_url\x18\x10 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RegionInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REGIONINFO']._serialized_start=21
  _globals['_REGIONINFO']._serialized_end=410
# @@protoc_insertion_point(module_scope)
