# SDKServer-config
Setting:
  ssl: true                             # 启用SSL（https）模式
  ssl_self_signed: true                 # 启用自签模式
  listen: "0.0.0.0"
  port: 21000
  reload: true
  debug: true
  threaded: true
  high_frequency_logs: false             # sdk是否启用高频日志
  cdkexchange: true                      # 启用CDK兑换功能
Database:
  mysql:
    host: 127.0.0.1
    user: root
    port: 5000
    account_library_name: hk4e-accounts-cokeserver
    exchcdk_library_name: hk4e-cdk-cokeserver
    announce_library_name: hk4e-announce-cokeserver
    password: cokeserver2022
  redis:
    host: 127.0.0.1
    port: 6379
    password: cokeserver2022
Login:
  disable_mmt: true                     # 禁用验证码
  disable_regist: false                 # 禁用注册功能
  disable_email_bind_skip: true         # 禁用跳过电子邮件绑定
  enable_email_captcha: false           # 启用电子邮件验证码
  enable_ps_bind_account: false         # 启用账号绑定功能
  email_bind_remind: false              # 启用电子邮件绑定提醒
  email_verify: false                   # 启用电子邮件验证
  realperson_required: false            # 需要真实身份验证
  safe_mobile_required: false           # 需要安全手机验证
  device_grant_required: false          # 新设备登录验证
  initialize_firebase: true             # 是否初始化Firebase(用户认证、实时数据库、云存储等)
  bbs_auth_login: true                  # BBS 认证登录
  fetch_instance_id: true               # 登录时获取设备ID
  enable_flash_login: true              # 闪电登录
Player:
  disable_ysdk_guard: false             # 禁用游戏防沉迷系统(提醒游戏时长)
  enable_announce_pic_popup: true       # 启用弹窗
  protocol: true                        # 启用协议
  qr_enabled: false                     # 启用二维码功能
  qr_bbs: false                         # BBS 二维码登录
  qr_cloud: false                       # 云原神二维码登录
  enable_user_center: true              # 玩家中心
  guardian_required: false              # 需要家长验证
  realname_required: false              # 需要实名验证
  heartbeat_required: true              # 发送心跳包
Reddot:
  display: false                        # 游戏内是否显示红点
Announce:
  remind: true                          # 登入游戏公告提醒
  alert: true                           # 游戏内弹窗公告
  extra_remind: true                    # 额外提醒
Security:
  access_limits: 100                    # 单个IP在1分钟内对路由的最高访问频次
  verify_code_length: 4                 # 验证码位数
  ticket_length: 40                     # ticket 位数
  token_length: 32                      # token 位数
  min_password_len: 8                   # 对应客户端 mhypbase.ini 的 PublicRSAKey
Auth:
  enable_password_verify: false         # 启用密码验证
  enable_guest: true                    # 启用游客登录
Other:
  modified: true                        # 追踪对象或实体的变更状态或时间
  serviceworker: true                   # 启用分析
  new_register_page_enable: true
  kcp_enable: true
  enable_web_dpi: true
  list_price_tierv2_enable: true
Muipserver:
  is_ssl: false                         # 全局配置 / https 模式
  address: 192.168.1.2
  region: cn_gf01
  port: 21041
  sign: cokeserver2022
Dispatch:
  list:
    cn_gf01: "http://192.168.1.2:21041"
    cn_gf02: "https://192.168.1.2:21000"
Region:
  - name: cn_gf01
    title: Live-01
    dispatchUrl: http://127.0.0.1:21000/query_region/cn_gf01
  - name: cn_gf02
    title: Live-02
    dispatchUrl: http://192.168.1.2:21041/query_cur_region
  - name: cn_gf03
    title: Live-03
    dispatchUrl: http://192.168.1.2:21041/query_cur_region
Gateserver:
  - ip: 192.168.1.2
    port: 3306
  - ip: 192.168.1.0
    port: 3307
  - ip: 114.514.114.514
    port: 11451
Mail:
  ENABLE: true                       # 用于注册的邮件功能
  MAIL_SERVER: "smtp.qq.com"
  MAIL_PORT: 587
  MAIL_USE_TLS: true
  MAIL_USE_SSL: false
  MAIL_USERNAME: "cokeserver@qq.com"
  MAIL_PASSWORD: ""
  MAIL_DEFAULT_SENDER: "CokeSR"
