# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QueryCurrRegionHttpRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ForceUpdateInfo_pb2 as ForceUpdateInfo__pb2
import StopServerInfo_pb2 as StopServerInfo__pb2
import RegionInfo_pb2 as RegionInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cQueryCurrRegionHttpRsp.proto\x1a\x15\x46orceUpdateInfo.proto\x1a\x14StopServerInfo.proto\x1a\x10RegionInfo.proto\"\xb6\x01\n\x16QueryCurrRegionHttpRsp\x12\x0f\n\x07retcode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12(\n\x0c\x66orce_udpate\x18\x03 \x01(\x0b\x32\x10.ForceUpdateInfoH\x00\x12&\n\x0bstop_server\x18\x04 \x01(\x0b\x32\x0f.StopServerInfoH\x00\x12\"\n\x0bregion_info\x18\x05 \x01(\x0b\x32\x0b.RegionInfoH\x00\x42\x08\n\x06\x64\x65tailb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'QueryCurrRegionHttpRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUERYCURRREGIONHTTPRSP']._serialized_start=96
  _globals['_QUERYCURRREGIONHTTPRSP']._serialized_end=278
# @@protoc_insertion_point(module_scope)
