# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QueryRegionListHttpRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RegionSimpleInfo_pb2 as RegionSimpleInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cQueryRegionListHttpRsp.proto\x1a\x16RegionSimpleInfo.proto\"o\n\x16QueryRegionListHttpRsp\x12\x0f\n\x07retcode\x18\x01 \x01(\x05\x12&\n\x0bregion_list\x18\x02 \x03(\x0b\x32\x11.RegionSimpleInfo\x12\x1c\n\x14\x63lient_custom_config\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'QueryRegionListHttpRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUERYREGIONLISTHTTPRSP']._serialized_start=56
  _globals['_QUERYREGIONLISTHTTPRSP']._serialized_end=167
# @@protoc_insertion_point(module_scope)
