# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResVersionConfig_v2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19ResVersionConfig_v2.proto\x12\nproto.live\"\xa5\x01\n\x13ResVersionConfig_v2\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x0f\n\x07relogin\x18\x02 \x01(\x08\x12\x0b\n\x03md5\x18\x03 \x01(\t\x12\x1a\n\x12release_total_size\x18\x04 \x01(\t\x12\x16\n\x0eversion_suffix\x18\x05 \x01(\t\x12\x0e\n\x06\x62ranch\x18\x06 \x01(\t\x12\x1b\n\x13next_script_version\x18\x07 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ResVersionConfig_v2_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RESVERSIONCONFIG_V2']._serialized_start=42
  _globals['_RESVERSIONCONFIG_V2']._serialized_end=207
# @@protoc_insertion_point(module_scope)
