# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ForceUpdateInfo_v1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x46orceUpdateInfo_v1.proto\x12\tproto.cbt\"L\n\x12\x46orceUpdateInfo_v1\x12\x18\n\x10\x66orce_update_url\x18\x01 \x01(\t\x12\x1c\n\x14\x63lient_custom_config\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ForceUpdateInfo_v1_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FORCEUPDATEINFO_V1']._serialized_start=39
  _globals['_FORCEUPDATEINFO_V1']._serialized_end=115
# @@protoc_insertion_point(module_scope)
