# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QueryRegionListHttpRsp_v1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import src.proto.cbt.RegionSimpleInfo_v1_pb2 as RegionSimpleInfo__v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fQueryRegionListHttpRsp_v1.proto\x12\tproto.cbt\x1a\x19RegionSimpleInfo_v1.proto\"\x7f\n\x19QueryRegionListHttpRsp_v1\x12\x0f\n\x07retcode\x18\x01 \x01(\x05\x12\x33\n\x0bregion_list\x18\x02 \x03(\x0b\x32\x1e.proto.cbt.RegionSimpleInfo_v1\x12\x1c\n\x14\x63lient_custom_config\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'QueryRegionListHttpRsp_v1_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUERYREGIONLISTHTTPRSP_V1']._serialized_start=73
  _globals['_QUERYREGIONLISTHTTPRSP_V1']._serialized_end=200
# @@protoc_insertion_point(module_scope)
