# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StopServerInfo_v1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17StopServerInfo_v1.proto\x12\tproto.cbt\"C\n\x11StopServerInfo_v1\x12\x17\n\x0fstop_begin_time\x18\x01 \x01(\r\x12\x15\n\rstop_end_time\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StopServerInfo_v1_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STOPSERVERINFO_V1']._serialized_start=38
  _globals['_STOPSERVERINFO_V1']._serialized_end=105
# @@protoc_insertion_point(module_scope)
