# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RegionInfo_v2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import data.proto.live.ResVersionConfig_v2_pb2 as ResVersionConfig__v2__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13RegionInfo_v2.proto\x12\nproto.live\x1a\x19ResVersionConfig_v2.proto\"\xce\x06\n\rRegionInfo_v2\x12\x15\n\rgateserver_ip\x18\x01 \x01(\t\x12\x17\n\x0fgateserver_port\x18\x02 \x01(\r\x12\x18\n\x10pay_callback_url\x18\x03 \x01(\t\x12\x11\n\tarea_type\x18\x07 \x01(\t\x12\x14\n\x0cresource_url\x18\x08 \x01(\t\x12\x10\n\x08\x64\x61ta_url\x18\t \x01(\t\x12\x14\n\x0c\x66\x65\x65\x64\x62\x61\x63k_url\x18\n \x01(\t\x12\x14\n\x0c\x62ulletin_url\x18\x0b \x01(\t\x12\x18\n\x10resource_url_bak\x18\x0c \x01(\t\x12\x14\n\x0c\x64\x61ta_url_bak\x18\r \x01(\t\x12\x1b\n\x13\x63lient_data_version\x18\x0e \x01(\r\x12\x14\n\x0chandbook_url\x18\x10 \x01(\t\x12#\n\x1b\x63lient_silence_data_version\x18\x12 \x01(\r\x12\x17\n\x0f\x63lient_data_md5\x18\x13 \x01(\t\x12\x1f\n\x17\x63lient_silence_data_md5\x18\x14 \x01(\t\x12;\n\x12res_version_config\x18\x16 \x01(\x0b\x32\x1f.proto.live.ResVersionConfig_v2\x12\x12\n\nsecret_key\x18\x17 \x01(\x0c\x12\x1e\n\x16official_community_url\x18\x18 \x01(\t\x12\x1d\n\x15\x63lient_version_suffix\x18\x1a \x01(\t\x12%\n\x1d\x63lient_silence_version_suffix\x18\x1b \x01(\t\x12\"\n\x1ause_gateserver_domain_name\x18\x1c \x01(\x08\x12\x1e\n\x16gateserver_domain_name\x18\x1d \x01(\t\x12\x17\n\x0fuser_center_url\x18\x1e \x01(\t\x12\x18\n\x10\x61\x63\x63ount_bind_url\x18\x1f \x01(\t\x12\x11\n\tcdkey_url\x18  \x01(\t\x12\x1a\n\x12privacy_policy_url\x18! \x01(\t\x12\x19\n\x11next_resource_url\x18\" \x01(\t\x12@\n\x17next_res_version_config\x18# \x01(\x0b\x32\x1f.proto.live.ResVersionConfig_v2\x12\x10\n\x08game_biz\x18$ \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RegionInfo_v2_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REGIONINFO_V2']._serialized_start=63
  _globals['_REGIONINFO_V2']._serialized_end=909
# @@protoc_insertion_point(module_scope)
