# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StopServerInfo_v2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17StopServerInfo_v2.proto\x12\nproto.live\"e\n\x11StopServerInfo_v2\x12\x17\n\x0fstop_begin_time\x18\x01 \x01(\r\x12\x15\n\rstop_end_time\x18\x02 \x01(\r\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x13\n\x0b\x63ontent_msg\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StopServerInfo_v2_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STOPSERVERINFO_V2']._serialized_start=39
  _globals['_STOPSERVERINFO_V2']._serialized_end=140
# @@protoc_insertion_point(module_scope)
